[package]
name = "ignite"
version = "0.4.0"
edition = "2024"

[dependencies]
log = "0.4.17"
goblin = { version = "0.10.4", default-features = false, features = [
    "elf32",
    "elf64",
    "endian_fd",
] }
bitflags = "2.4"
x86_64 = "0.15.4"
syscall = { path = "../libs/syscall" }

[features]
live = []
