[package]
name = "ignite"
version = "0.2.0"
edition = "2024"

[dependencies]
uefi = { version = "0.28.0", features = ["alloc"] }
uefi-services = "0.25.0"
log = "0.4"
goblin = { version = "0.8", default-features = false, features = [
    "elf32",
    "elf64",
    "endian_fd",
] }
bitflags = "2.4"
x86_64 = "0.14"
syscall = { path = "../libs/syscall" }

[features]
live = []
