[toolchain]
channel = "nightly"
# components "rust-src" é obrigatório para recompilar core/alloc para UEFI
# llvm-tools-preview permite criar imagens de disco e inspecionar binários
components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]
# Alvo padrão para facilitar cargo build
targets = ["x86_64-unknown-uefi"]
